### PR TITLE
Add Git cloning instructions.

### PR DESCRIPTION
**Pull request by wormeyman**

### CODE REVIEW

**Comment by MiguelCastillo** [comment]
@wormeyman Do you think you can add a note to make sure that the themes-v1 is the correct branch?

**Comment by wormeyman** [comment]
It works for me on the master branch of your fork, should i be using the themes-v1 branch?

**Comment by wormeyman** [comment]
`git clone https://github.com/MiguelCastillo/brackets.git -b themes-v1 /bracketsThemes`

What do you think about that?

**Comment by MiguelCastillo** [comment]
Master will work, but its a few commits behind.  Its for the original PR I did, but we decided to do another PR because the original PR  had toooo many comments.  The new PR is themes-v1.

I like this last git clone, let's do it!

**Comment by wormeyman** [comment]
ok i updated my pull request including the change directory part.

**Comment by MiguelCastillo** [comment]
Awesome!  Thank you Eric.

**Comment by MiguelCastillo** [comment]
So, are you running themes in core right now?

**Comment by wormeyman** [comment]
What do you mean by running themes in core? After this thread i switched to your branch from your fork. I also had to `git pull --rebase origin themes-v1` since my branch was from June for some reason.

**Comment by MiguelCastillo** [comment]
Oh yeah, so themes-v1 is going to be merged into brackets core in the next few days.  We wanted to do it yesterday, but we found some bugs I needed to fix.

So, themes-v1 is running Themes in Brackets core.  Meaning is part of the product and not an extension.

**Comment by wormeyman** [comment]
Must be exciting that this is getting merged soon, you have been working on this for a while! So once this is merged we can run it off of the official brackets repo on the master branch?

**Comment by MiguelCastillo** [comment]
Yeah, it's taken longer than I'd like to.  There was other stuff I had to address Brackets core like a new font API and figure out how to smoothly allow theme authors to mixin pre-configured colors we are going to ship and stuff.  For example, this is a good way to use some of the pre-defined color schemes we will be providing.
https://github.com/MiguelCastillo/brackets/blob/themes-v1/src/extensions/default/ThorDarkTheme/main.less

So, it's been a lot of work.

But yeah, correct, you will be running it off the official master branch.  We are planning on shipping it in sprint 42, which is really exciting :)

**Comment by wormeyman** [comment]
I'll take a look at the `ThorDarkTheme/main.less` don't forget to update the :copyright: year if that is going to be merged into core.

**Comment by MiguelCastillo** [comment]
Ah yes, I should do that.  The Thor themes are two themes we will be shipping with initially.

**Comment by wormeyman** [comment]
I tried the Thor theme and probably because of the symlinks on windows it cannot locate the less files at the beginning. Any thoughts?

cant-get-less

**Comment by MiguelCastillo** [comment]
Oh yeah, look at that.  Some Windows Lovin'.  Yeah, the issue might be the symlink.  So, what seems to be happening is that the Less processor is having problems figuring out the import statements I am giving it.  I need to setup my Window machine to dig in

**Comment by wormeyman** [comment]
This is what i ended up doing to get my tests working right:

``` css
// Brackets-specific default font and color definitions
@import url("/Program Files (x86)/Brackets/dev/src/styles/brackets_colors.less");

// Default theme -- all UI styling comes from variables in a theme
// Themes can rely on variables defined above
@import url("/Program Files (x86)/Brackets/dev/src/styles/brackets_theme_default.less");

// Include Codemirror styling overrides so that we can overrides proper values
// for the theme.  If you need to customize the tree, you also include jsTree.less
// and even brackets_scrollbars.less
@import url("/Program Files (x86)/Brackets/dev/src/styles/brackets_codemirror_override.less");
```

**Comment by MiguelCastillo** [comment]
Yeah, that's really not what I was hoping would be the usability for it.  I will have time to look into that tomorrow.  I am really hoping that it is a simple fix :/

**Comment by MiguelCastillo** [comment]
@wormeyman Hey dude, I fixed the issue in Brackets for now.  The bug is in the less processor and I will be submitting a PR for it shortly.  Do you mind getting latest and giving this another try, please?

**Comment by wormeyman** [comment]
It did not work for me. 
brackets-less-problem

https://github.com/wormeyman/RubyBlue/blob/master/RubyBlueTheme.less

**Comment by MiguelCastillo** [comment]
Let's do this.  Send me the git branch for your theme and I will debug it to figure out what's going south

**Comment by MiguelCastillo** [comment]
I am losing it dude, sorry I just saw the the link :)

**Comment by MiguelCastillo** [comment]
@wormeyman Hey, I was able to load your theme using the imports without specifying the full path.  Its odd that you are having problems with it.  What version of windows are you using?  I tested with windows7 and windows8.1

BTW, you may as well switch back to brackets main branch.

**Comment by wormeyman** [comment]
I just switched to brackets main branch and it works. Windows 8.1 by the way.

I'm getting closer to having it ready to submit, would you like me to transfer ownership of the theme with all of my development history or move it to the brackets-themes organization fresh?

Also thanks for all the help!

**Comment by MiguelCastillo** [comment]
Its up to you to leave the history. I would... So that you and other people can see it.  But its totally up to you.

Go ahead transfer away!  You are a contributor in the organization. :)

**Comment by MiguelCastillo** [comment]
@wormeyman And thank you for testing and helping, I really appreciate it Eric.

**Comment by wormeyman** [comment]
Am i supposed to keep the Adobe copyright header in the file? Or should i switch my name into it?

**Comment by MiguelCastillo** [comment]
That theme is yours, so make sure you give yourself all the credit

**Comment by MiguelCastillo** [comment]
Good point too, so I added the copyright notice to the themes I created in this group and also added it to boilerplate

https://github.com/Brackets-Themes/BoilerPlate/blob/master/main.less

**Comment by wormeyman** [comment]
Sounds good, one thing that is really bugging me about this development version is that it is harder to debug themes because you cannot inspect a line any more you hit a `div` that is inside of `.CodeMirror-sizer` and then you have to drill down inside of the elements view. Does that make sense?

**Comment by MiguelCastillo** [comment]
Yeah, so what you do is comment out this line https://github.com/adobe/brackets/blob/master/src/styles/brackets_codemirror_override.less#L129

Reload and you should be able to inspect a bit better.

**Comment by wormeyman** [comment]
Ok i transferred my theme but i appear not to have write access to it?

**Comment by MiguelCastillo** [comment]
Ok cool, now I know what happens when someone transfers the theme.  I have to explicitly add the collaborator team to have write access.  This is a great pilot theme transfer.

**Pull request merged**
